### ISSUE TITLE
Request: More World Generation Events

### ISSUE THREAD

**Issue by AJ4real** [PolyhedralDev/Terra#134]
Please add the following to your API, I would really appreciate it.

- [ ] Event that is fired when a tree is generated in the world
     - [ ] Method that returns `HashMap<Location, Material>` for what material was generated at what location
     - [ ] Method that returns `String` for the Object ID of what tree has been generated
- [ ] Event that is fired when an ore is placed in the world
     - [ ] Method that returns `HashMap<Location, Material>` for what material was generated at what location
     - [ ] Method that returns `String` for the Object ID of what ore has been generated

**Comment by solonovamax** [comment]
Those hashmaps sound horrible, but the rest is plausible.

But I'm sure we could do something with the same effect.

**Comment by dfsek** [comment]
Those events can be implemented, but will definitely be made stateless. If you want to change how those objects generate, implement `Tree` or extend `Ore` and insert your implementation into a registry, then use it in a pack. You shouldn't change behaviour invisibly, *especially* when there is a clear, supported, and expected way to do the same thing.   

For the trees, an `ImmutableBuffer` could be implemented and passed to the event, but due to how ores generate it is impractical to re-generate them into a buffer. If you need to *view* the blocks, you can generate the `Ore` passed to the event in a dummy world.

**Comment by solonovamax** [comment]
IMO, it shouldn't pass the buffer for trees.

**Comment by dfsek** [comment]
ores and trees no longer explicitly exist.
