### ISSUE TITLE
Add compatibility with the mod Valhelsia Structures.

### ISSUE THREAD

**Issue by Skelark** [PolyhedralDev/Terra#193]
The mod Valhelsia Structures adds a few good looking vanilla like buildings to the world. Is it possible to create an addon to add compatibility with this mod?

**Comment by M3RGeo** [comment]
Valhesia Structures should now spawn without any need for an addon due to https://github.com/PolyhedralDev/Terra/pull/191.
Which is included in the latest update, at least for fabric.

I haven't tested this yet, but from what I understand it should just work without having to change anything in the packs.

**Comment by solonovamax** [comment]
Other mods are incompatible mainly due to the fact that Terra acts as a total replacement of vanilla world generation (which by design allows it to be more maintainable, flexible, and feature-full) compared to other mods & plugins which instead hook into vanilla generation.

Because of this, it is very difficult, if not impossible, to make terra work with other mods than modify generation.

This is not an issue.
