### ISSUE TITLE
[Feature] Make the NOISE_3D generator biome:ocean parameters optional

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#295]
Currently, the `ocean` parameters are required to be defined for every biome config which makes the assumption that the config dev wants some kind of ocean present in their world. This may not be the case and so the config dev is required to set these parameters to something redundant like `ocean.palette` to `BLOCK:minecraft:air`.

**Comment by solonovamax** [comment]
^ with that, why have concepts like "ocean" at all?

It would be much better if we instead used a concept like "fill everything below this y level"
yes, that's what the oceans do, but that would be more extensible. Especially if you could say "fill it with a certain palette"  rather than just 1 block type

**Comment by dfsek** [comment]
that's already how the config works.

**Comment by dfsek** [comment]
implemented in aa5ccd01965c2cb08ffaabc1f6de58c0b0aa4a10

**Comment by solonovamax** [comment]
> that's already how the config works.

oh sick, just making sure lol
