### ISSUE TITLE
Large image support

### ISSUE THREAD

**Issue by Gal1leooo** [PolyhedralDev/Terra#373]
## Describe the issue

There is an error when i try to generate a world using provider type: image
The image is 25000x25000
Error: https://mclo.gs/MIY81FW

The files were .yml but i can't upload them, so i converted in txt
[image.txt](https://github.com/PolyhedralDev/Terra/files/9640637/image.txt)
[pack.txt](https://github.com/PolyhedralDev/Terra/files/9640638/pack.txt)

**Comment by solonovamax** [comment]
Send the entire pack folder, including the image you used. Zip all the files, so you can upload them as a single file.

**Comment by Astrashh** [comment]
I believe the issue is with how the image is being loaded via Java's `BufferedImage` class, specifically that exception seems to be thrown when images are too large to be stored in memory (since each image sample point is stored in an array limited by the max integer size)

A solution would be to implement image stitching (which would be invisible to users) in the backend for images that are too large, such that they can be loaded into memory as multiple smaller `BufferedImage`s.

**Comment by Astrashh** [comment]
I would recommend implementing on top of https://github.com/PolyhedralDev/Terra/pull/356 if anyone else wishes to work on this

**Comment by Gal1leooo** [comment]
Thanks so much for the support! Still need the full pack? In case I'd prefer to send it in private.
If I may ask, how soon will this bug be fixed?

**Comment by nihiluis** [comment]
hope #356 doesnt get stale. rn, I think the image provider is not usable

**Comment by Astrashh** [comment]
Stitching implemented in 6efff02c19ef089d5d74df5ce4f30067afcab9f8
