### ISSUE TITLE
[Feature] Use the "Customize" button for packs.

### ISSUE THREAD

**Issue by yum13241** [PolyhedralDev/Terra#446]
- [x] I have checked that I am on the latest version of Terra.
- [X] I have searched github for similar features requests, including closed
  ones, and found none.
- [X] I believe this is within the scope of Terra.
- [X] This feature request is for *all* of Terra, and isn't something that
  should be implemented by a pack or addon.

---

### Feature Description
Rather than having to click the "World Type" button many times, you could make it say "World Type: Terra" and then the "Customize" button could just show all packs.

### What Problem Does This Solve?

Having to 1. Wait ages for the ticker text 2. Clicking many times, then accidentally miss it, ad infinitum (or until I get it)

### A Solution You'd Like

Making the "World Type" button say "World Type: Terra" when Terra is selected, then make the "Customize" button clickable, and allow us to choose packs from there, akin to the vanilla "Single Biome" type.

Imagine if you had to click 64 times to get the biome you wanted, only to click twice on accident and have to do it again!

### Alternative Solutions

1. Being patient
2. Clicking slowly

*Thank you for reading!

**Comment by duplexsystem** [comment]
I do not think this is possible because of how we have to register dimensions and such. In addition, we want consistent UX between server and client which this would split unless we made servers, what most Terra users use, more complicated to configure. However, I do agree that the text ticker needs to be clearer, however this is planned to be fixed with our translation library. So please open a separate issue for the ticker text being too long.
